#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: meson
# autospec version: v21
# autospec commit: fbbd4e3
#
Name     : sane-airscan
Version  : 0.99.33
Release  : 4
URL      : https://github.com/alexpevzner/sane-airscan/archive/0.99.33/sane-airscan-0.99.33.tar.gz
Source0  : https://github.com/alexpevzner/sane-airscan/archive/0.99.33/sane-airscan-0.99.33.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-2.0
Requires: sane-airscan-bin = %{version}-%{release}
Requires: sane-airscan-data = %{version}-%{release}
Requires: sane-airscan-lib = %{version}-%{release}
Requires: sane-airscan-license = %{version}-%{release}
Requires: sane-airscan-man = %{version}-%{release}
BuildRequires : buildreq-meson
BuildRequires : gnutls-dev
BuildRequires : pkgconfig(avahi-client)
BuildRequires : pkgconfig(gnutls)
BuildRequires : pkgconfig(libjpeg)
BuildRequires : pkgconfig(libpng)
BuildRequires : pkgconfig(libtiff-4)
BuildRequires : pkgconfig(libxml-2.0)
BuildRequires : pkgconfig(sane-backends)
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
# sane-airscan -- SANE backend for AirScan (eSCL) and WSD document scanners
Similar to how most modern network printers support "driverless" printing,
using the universal vendor-neutral printing protocol, many modern network
scanners and MFPs support "driverless" scanning.

%package bin
Summary: bin components for the sane-airscan package.
Group: Binaries
Requires: sane-airscan-data = %{version}-%{release}
Requires: sane-airscan-license = %{version}-%{release}

%description bin
bin components for the sane-airscan package.


%package data
Summary: data components for the sane-airscan package.
Group: Data

%description data
data components for the sane-airscan package.


%package lib
Summary: lib components for the sane-airscan package.
Group: Libraries
Requires: sane-airscan-data = %{version}-%{release}
Requires: sane-airscan-license = %{version}-%{release}

%description lib
lib components for the sane-airscan package.


%package license
Summary: license components for the sane-airscan package.
Group: Default

%description license
license components for the sane-airscan package.


%package man
Summary: man components for the sane-airscan package.
Group: Default

%description man
man components for the sane-airscan package.


%prep
%setup -q -n sane-airscan-0.99.33
cd %{_builddir}/sane-airscan-0.99.33

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1742437140
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export GOAMD64=v2
meson --libdir=lib64 --prefix=/usr --buildtype=plain   builddir
ninja -v -C builddir

%install
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export GOAMD64=v2
mkdir -p %{buildroot}/usr/share/package-licenses/sane-airscan
cp %{_builddir}/sane-airscan-%{version}/COPYING %{buildroot}/usr/share/package-licenses/sane-airscan/4cc77b90af91e615a64ae04893fdffa7939db84c || :
GOAMD64=v2
DESTDIR=%{buildroot} ninja -C builddir install
## install_append content
# Move sane config elements from /etc to /usr/share/defaults
mkdir -p %{buildroot}/usr/share/defaults/sane/dll.d
mv %{buildroot}/etc/sane.d/*.conf %{buildroot}/usr/share/defaults/sane/
mv %{buildroot}/etc/sane.d/dll.d/* %{buildroot}/usr/share/defaults/sane/dll.d/
## install_append end

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/airscan-discover

%files data
%defattr(-,root,root,-)
/usr/share/defaults/sane/airscan.conf
/usr/share/defaults/sane/dll.d/airscan

%files lib
%defattr(-,root,root,-)
/usr/lib64/sane/libsane-airscan.so
/usr/lib64/sane/libsane-airscan.so.1

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/sane-airscan/4cc77b90af91e615a64ae04893fdffa7939db84c

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/airscan-discover.1
/usr/share/man/man5/sane-airscan.5
